name: Learn basic of GitHub Action

on:
  push:
    branches:
      -  main

jobs:
  api-gateway:
    runs-on: ubuntu-latest

    steps:
    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker image
      run: mvn docker:build
